export async function seed(knex) {
  await knex('missing_cats').insert([
    {
      microchip: true,
      microchip_number: 'ABC123',
      user_id_mc: 1,
      cat_name: 'Fluffy',
      breed: 'Persian',
      color: 'White',
      description: 'Fluffy and friendly cat with blue eyes',
      date_lost: '2023-01-15',
      location: '40.7128, -74.0060',
      cat_missing: false,
    },
    {
      microchip: false,
      microchip_number: 'EFG678',
      user_id_mc: 2,
      cat_name: 'Whiskers',
      breed: 'Siamese',
      color: 'Brown',
      description: 'Energetic cat with distinctive whiskers',
      date_lost: '2023-02-20',
      location: '34.0522, -118.2437',
      cat_missing: true,
    },
    {
      microchip: true,
      microchip_number: 'XYZ789',
      user_id_mc: 3,
      cat_name: 'Mittens',
      breed: 'Tabby',
      color: 'Gray',
      description: 'Mittens is a playful and curious cat',
      date_lost: '2023-03-10',
      location: '41.8781, -87.6298',
      cat_missing: false,
    },
    {
      microchip: true,
      microchip_number: 'DEF456',
      user_id_mc: 4,
      cat_name: 'Shadow',
      breed: 'Black Cat',
      color: 'Black',
      description: 'Shadow is a mysterious black cat with golden eyes',
      date_lost: '2023-04-05',
      location: '37.7749, -122.4194',
      cat_missing: false,
    },
  ])
}
