export async function seed(knex) {
  await knex('sighted_cats').insert([
    {
      sighted_cat_id: 1,
      user_id_sc: 1,
      cat_id_mc: 1,
      color: 'White',
      description: 'Friendly white cat with blue eyes found near the park',
      date_seen: '2023-01-20',
      location_lat: '40.730610',
      location_lng: '-73.935242',
      email: 'founder@example.com',
    },
    {
      sighted_cat_id: 2,
      user_id_sc: 2,
      cat_id_mc: 2,
      color: 'Brown',
      description: 'Brown Siamese cat found in the backyard',
      date_seen: '2023-02-25',
      location_lat: '34.052235',
      location_lng: '-118.243683',
      email: 'rescuer@example.com',
    },
    {
      sighted_cat_id: 3,
      user_id_sc: 3,
      cat_id_mc: 3,
      color: 'Gray',
      description: 'Gray tabby cat found playing near the street',
      date_seen: '2023-03-15',
      location_lat: '41.878113',
      location_lng: '-87.629799',
      email: 'saver@example.com',
    },
    {
      sighted_cat_id: 4,
      user_id_sc: 1,
      cat_id_mc: 4,
      color: 'Black',
      description: 'Mysterious black cat found on the rooftop',
      date_seen: '2023-04-10',
      location_lat: '37.774929',
      location_lng: '-122.419416',
      email: 'finder@example.com',
    },
    {
      sighted_cat_id: 5,
      user_id_sc: 4,
      cat_id_mc: 1,
      color: 'White',
      description: 'Lost white cat with a blue collar found near the church',
      date_seen: '2023-05-05',
      location_lat: '40.712776',
      location_lng: '-74.005974',
      email: 'catlover@example.com',
    },
    {
      sighted_cat_id: 6,
      user_id_sc: 2,
      cat_id_mc: 2,
      color: 'Brown',
      description: 'Adorable brown cat found on the porch',
      date_seen: '2023-06-20',
      location_lat: '33.749001',
      location_lng: '-84.387978',
      email: 'animalrescue@example.com',
    },
    {
      sighted_cat_id: 7,
      user_id_sc: 2,
      cat_id_mc: 3,
      color: 'Gray',
      description: 'Lost gray cat with a red collar found in the garden',
      date_seen: '2023-07-10',
      location_lat: '39.952583',
      location_lng: '-75.165222',
      email: 'petfinder@example.com',
    },
    {
      sighted_cat_id: 8,
      user_id_sc: 3,
      cat_id_mc: 4,
      color: 'Black',
      description: 'Black cat with yellow eyes found near the woods',
      date_seen: '2023-08-15',
      location_lat: '32.776272',
      location_lng: '-96.796875',
      email: 'foundcat@example.com',
    },
    {
      sighted_cat_id: 9,
      user_id_sc: 1,
      cat_id_mc: 1,
      color: 'White',
      description: 'White cat found in the neighborhood',
      date_seen: '2023-09-05',
      location_lat: '41.878113',
      location_lng: '-87.629799',
      email: 'helpthecats@example.com',
    },
    {
      sighted_cat_id: 10,
      user_id_sc: 1,
      cat_id_mc: 2,
      color: 'Brown',
      description: 'Brown cat with a fluffy tail found in the park',
      date_seen: '2023-10-10',
      location_lat: '37.774929',
      location_lng: '-122.419416',
      email: 'catrescue@example.com',
    },
  ])
}
