export async function seed(knex) {
  await knex('sighted_cats').insert([
    {
      sighted_cat_id: 1,
      user_id_sc: 1,
      cat_id_mc: 1,
      color: 'White',
      description: 'Friendly white cat with blue eyes found near the park',
      date_seen: '2023-01-20',
      location: '40.730610, -73.935242',
      sighted_cat_phone: '022-021-2355',
      sighted_cat_email: 'founder@example.com',
      sighted_image_url: 'server/images/sighted_cats/fluffy2_persian.jpeg',
    },
    {
      sighted_cat_id: 2,
      user_id_sc: 2,
      cat_id_mc: 2,
      color: 'Brown',
      description: 'Brown Siamese cat found in the backyard',
      date_seen: '2023-02-25',
      location: '34.052235, -118.243683',
      sighted_cat_phone: '022-021-2355',
      sighted_cat_email: 'rescuer@example.com',
      sighted_image_url: 'server/images/sighted_cats/whiskers_siamese2.jpg',
    },
    {
      sighted_cat_id: 3,
      user_id_sc: 3,
      cat_id_mc: 3,
      color: 'Gray',
      description: 'Gray tabby cat found playing near the street',
      date_seen: '2023-03-15',
      location: '41.878113, -87.629799',
      sighted_cat_phone: '022-021-2355',
      sighted_cat_email: 'saver@example.com',
      sighted_image_url: 'server/images/sighted_cats/mittens_tabby2.webp',
    },
    {
      sighted_cat_id: 4,
      user_id_sc: 1,
      cat_id_mc: 4,
      color: 'Black',
      description: 'Mysterious black cat found on the rooftop',
      date_seen: '2023-04-10',
      location: '37.774929, -122.419416',
      sighted_cat_phone: '022-021-2355',
      sighted_cat_email: 'finder@example.com',
      sighted_image_url: 'server/images/sighted_cats/shadow_blackcat2.jpg',
    },
    {
      sighted_cat_id: 5,
      user_id_sc: 4,
      cat_id_mc: 1,
      color: 'White',
      description: 'Lost white cat with a blue collar found near the church',
      date_seen: '2023-05-05',
      location: '40.712776, -74.005974',
      sighted_cat_phone: '022-021-2355',
      sighted_cat_email: 'catlover@example.com',
      sighted_image_url: 'server/images/sighted_cats/fluffy3.jpeg',
    },
  ])
}
